### ISSUE TITLE
legendre_Pl_array and legendre_Pl_deriv_array are broken

### ISSUE THREAD

**Issue by H-M-H** [GuillaumeGomez/rust-GSL#129]
The [gsl docs](https://www.gnu.org/software/gsl/doc/html/specfunc.html?highlight=legendre#c.gsl_sf_legendre_Pl_array) state:
> These functions compute arrays of Legendre polynomials P_l(x) and derivatives dP_l(x)/dx for l = 0, \dots, lmax and |x| \le 1.

That is the parameter `l` is not the size of the array for the results. Thus the following is wrong:
https://github.com/GuillaumeGomez/rust-GSL/blob/c21148fc63946dfa8a19e9894d830fd6de28ce33/src/legendre.rs#L75

Like that gsl tries to write to the address after the last array element resulting in undefined behavior.

**Comment by GuillaumeGomez** [comment]
Indeed, thanks!
