### ISSUE TITLE
glfixed_point is broken

### ISSUE THREAD

**Issue by H-M-H** [GuillaumeGomez/rust-GSL#130]
`gsl_integration_glfixed_point` only returns a single (node, weight) pair and does not write all nodes and weights to arrays as implied here:
https://github.com/GuillaumeGomez/rust-GSL/blob/c21148fc63946dfa8a19e9894d830fd6de28ce33/src/types/integration.rs#L818-L824

**Comment by GuillaumeGomez** [comment]
The Rust binding is completely wrong and shouldn't take `xi` and `wi` as arguments.
