### ISSUE TITLE
request: Multidimensional Minimization

### ISSUE THREAD

**Issue by hugohp** [GuillaumeGomez/rust-GSL#144]
https://www.gnu.org/software/gsl/doc/html/multimin.html
Namelly Nelder and Mead

Any plans to introduce bindings to Multidimensional Minimization?

**Comment by hugohp** [comment]
I have a branch where I added "Multidimensional Minimizer" https://www.gnu.org/software/gsl/doc/html/multimin.html.
For now its only "functions without derivatives"
I think I need permission to raise a PR. Can you give me authorization please?

**Comment by hugohp** [comment]
When attempting to create a PR, it  asks me for a branch to compare against master but GH does not allow me to create a branch in this repo, nor can I "git push --set-upstream origin multimin"
Do I have to create a PR from a fork (instead of a branch)?

**Comment by GuillaumeGomez** [comment]
You can't push on this repository so you're expected to fork the repository in your account, push your work there and then make a pull request. Hope my explanations aren't confusing. ^^'

**Comment by hugohp** [comment]
Ok I've raised a PR. Thanks!
