### ISSUE TITLE
When is the next release? 

### ISSUE THREAD

**Issue by hugohp** [GuillaumeGomez/rust-GSL#155]

**Comment by GuillaumeGomez** [comment]
Since there are breaking changes, it'll be a new major release. As such, I'd like to wait for all breaking changes to be merged directly so I'm waiting on the feature suggested in https://github.com/GuillaumeGomez/rust-GSL/pull/153 to be done.

**Comment by hugohp** [comment]
Ok, thanks

**Comment by hugohp** [comment]
Closing

**Comment by Chris00** [comment]
A [new version of `gsl-sys` has been released](https://crates.io/crates/GSL-sys).  A new version of `gsl` will follow.

**Comment by Chris00** [comment]
@hugohp Do you need a new release for a particular purpose?  I'm asking because there is a lot of changes I'd still like to make before an (API breaking) release and that will take some time.  If there is a specific need, I may try to do an "intermediate" release.
