### ISSUE TITLE
Genericity over f32 and f64

### ISSUE THREAD

**Issue by golddranks** [GuillaumeGomez/rust-GSL#19]
I need to do a FFT to a buffer of f32 audio samples. To prevent needless copying and converting, it would be nice if rust-GSL provided genericity over f32 and f64.

If I understand GSL correctly, it needs to be built separately for 32-bit floats and 64-bit floats. However, I think that linking both libraries is possible, and thus, I think that having the APIs over a generic Float and impls for f32 calling the 32-bit version and impls for f64 calling the 64-bit version would be feasible.

What do you think?

**Comment by GuillaumeGomez** [comment]
I think it's a good idea. However I'm quite busy right now with gtk so, if you want it quickly, you'll have to do it yourself. Otherwise, I'll try to take a took in one or two week.

**Comment by golddranks** [comment]
I can try and look into it. However, I just realised that that specialised versions of the functions aren't (of course) going to work without the trait specialisation support which is slowly coming along, but still quite far off. Dang! Well, I'll try and think about this.

**Comment by GuillaumeGomez** [comment]
I was thinking to create a `Float` type alias (like you proposed) on `f32` or `f64`, depending of the option. However, replacing all `f32` will take a while (there are... a lot ^^).

**Comment by iduartgomez** [comment]
Somehow related to this, I was working with matrix operations and unfortunately the linear algebra ops use the double precision matrix while the BLAS ops use the float matrix.

I get this is a limitation or design with GSL itself but I wonder if there is someway to get around it doing some magic in rust with custom #[repr(C)] structs casting between f64 and f32 types to avoid unnecessary copying.

**Comment by GuillaumeGomez** [comment]
I don't have much time to work on this crate lately unfortunately... My primary focus for the moment is to make the binding to the `2.0` version. But if you have an idea on how to do this, I'd gladly accept a PR.

**Comment by GuillaumeGomez** [comment]
There are now `MatrixF32` and `MatrixF64` types as well as equivalent for other types. I can't make the GSL functions generic over them unfortunately though. So I think everything that could be done was already done.
