### ISSUE TITLE
enum 'EigenSort' is private

### ISSUE THREAD

**Issue by aalsuwaidi** [GuillaumeGomez/rust-GSL#20]
I am using the symmv_sort function to sort Eigenvalues + Eigenvectors, however I get an error saying that the EigenSort enum is private.

Looking at the source code on Github it's not private?

Also, the documentation page lists the enum under "rgsl::enums::EigenSort" but it's at "rgsl::enums::eigen_sort::EigenSort"?

**Comment by GuillaumeGomez** [comment]
I certainly forgot to reexport it.

**Comment by GuillaumeGomez** [comment]
@aalsuwaidi: I updated the enums system. Retry with "rgsl::enums::EigenSort".

**Comment by aalsuwaidi** [comment]
Still listed as private, I cloned the repository this morning and changed 
`mod enums` to `public mod enums` 
that got it to work

**Comment by GuillaumeGomez** [comment]
Oh my bad, actually, you can do directly: "rgsl::EigenSort". You're not supposed to import the enums module.

**Comment by aalsuwaidi** [comment]
Ah, it's working now. Thanks
