### ISSUE TITLE
Deprecated functions in GSL 2.0

### ISSUE THREAD

**Issue by wiep** [GuillaumeGomez/rust-GSL#30]
Since GSL 2.0 the functions
- gsl_bspline_deriv_alloc
- gsl_bspline_deriv_free
- gsl_sf_legendre_Plm_array
- gsl_sf_legendre_Plm_deriv_array
- gsl_sf_legendre_sphPlm_array
- gsl_sf_legendre_sphPlm_deriv_array
- gsl_sf_legendre_array_size

have been marked deprecated and will be removed in future [1]. Furthermore, gsl's default settings exclude deprecated functions from the build. Thus, linking rgsl against gsl 2.0 or newer is likely to fail, e.g. gsl 2.0+ provided via homebrew on a mac.

[1] http://git.savannah.gnu.org/cgit/gsl.git/tree/NEWS

**Comment by GuillaumeGomez** [comment]
For now I don't target the 2.0 version. I'll need to update my crate.

**Comment by GuillaumeGomez** [comment]
It should now work in 2.x version. You have to add v2 feature when building.
