### ISSUE TITLE
Windows building instruction missing

### ISSUE THREAD

**Issue by stiv-yakovenko** [GuillaumeGomez/rust-GSL#53]
I'd like to try this package on windows, but I don't see instruction how to build it...

**Comment by GuillaumeGomez** [comment]
https://github.com/GuillaumeGomez/rust-GSL#building

**Comment by stiv-yakovenko** [comment]
No, because previous step requires using apt-get on Linux with no corresponding step on Windows.

**Comment by GuillaumeGomez** [comment]
Hum good point. I'm adding it but I'll need you to confirm it for me. :)

**Comment by stiv-yakovenko** [comment]
The problem with windows is that windows has two toolchains: msvc and gnu. Gnu toolchain is the only way how you can debug your program with gdb (and thus with most IDEs). So you need special instruction how to build GSL with compiler from gnu toolchain (%HOME%\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\bin\gcc.exe)

**Comment by stiv-yakovenko** [comment]
some details on connecting blas: https://stackoverflow.com/questions/46004194/how-can-i-use-blas-on-windows-with-the-gnu-toolchain

**Comment by GuillaumeGomez** [comment]
Well, since I don't have windows, I can't do much to help you. :-/
