### ISSUE TITLE
bad link on crates.io

### ISSUE THREAD

**Issue by bburdette** [GuillaumeGomez/rust-GSL#55]
On crate.io the link to the latest build info ("You can also access the latest build of the documentation via the internet here.") is currently going to some celebrity news site:  http://rust-ci.org/GuillaumeGomez/rust-GSL/doc/rgsl/

**Comment by GuillaumeGomez** [comment]
Ah right. Thanks!

**Comment by GuillaumeGomez** [comment]
Hum no: https://crates.io/crates/GSL

**Comment by GuillaumeGomez** [comment]
I think you looked at the old one. I'll close this issue then. Thanks though!

**Comment by bburdette** [comment]
you're right!  I didn't see that it had been renamed, I was looking at rust-GSL 0.4.10 - didn't look past the first result.  Sorry for the trouble!

**Comment by GuillaumeGomez** [comment]
Closing it then.
