### ISSUE TITLE
Not Catching Bessel Underflows?

### ISSUE THREAD

**Issue by JP-Ellis** [GuillaumeGomez/rust-GSL#61]
I'm trying to use some of the Bessel functions and want to catch cases where they should underflow, and unfortunately it seems like the error is generated but not caught.

As a minimal example, here's a small program that uses the `K0_e` Bessel function

```rust
extern crate rgsl;

use rgsl::{bessel, Value};

fn main() {
    match bessel::K0_e(1e0) {
        (Value::Success, r) => println!("K0(1e0) = {:.3e}", r.val),
        _ => unimplemented!(),
    }

    match bessel::K0_e(1e3) {
        (Value::Success, r) => println!("K0(1e3) = {:.3e}", r.val),
        (Value::UnderFlow, r) => println!("K0(1e3) underflowed: {:.3e}", r.val),
        _ => unimplemented!(),
    }
}
```

and the output is:

```text
 ❯ cargo run
   Compiling gsl-bug v0.1.0 (/tmp/josh/gsl-bug)                                                                                                                                                                     
    Finished dev [unoptimized + debuginfo] target(s) in 0.38s                                                                                                                                                       
     Running `/home/josh/.cache/cargo/debug/gsl-bug`
K0(1e0) = 4.210e-1
gsl: exp.c:257: ERROR: underflow
Default GSL error handler invoked.
[1]    23445 abort (core dumped)  cargo run
```

Is this a bug with the Rust bindings to GSL, or is it an actual bug with GSL?

**Comment by GuillaumeGomez** [comment]
From the backtrace, I'd say it comes from the C code directly (since it prints a C file).

**Comment by JP-Ellis** [comment]
Well, the error ultimately arises from a call to `gsl_error()`.  By default, this prints a short debug message and aborts, and according to the documentation one really should define error handlers as described [in the GSL documentation](https://www.gnu.org/software/gsl/doc/html/err.html#error-handlers).  The problem is that I see no functionality to do so in this crate.

It should also be possible to call [`gsl_set_error_handler_off()`](https://www.gnu.org/software/gsl/doc/html/err.html#c.gsl_set_error_handler_off) so turn off all error handling and let errors propagate, but I don't know how/if that can be done within this crate either.

**Comment by GuillaumeGomez** [comment]
It seems like I didn't add them. I'll do that this evening.
