### ISSUE TITLE
Enforcing rust mutability rules ?

### ISSUE THREAD

**Issue by vberger** [GuillaumeGomez/rust-GSL#7]
Hi, I just started to look at this library planning to probably use it for some projects.

From what I see, for example `VectorF32::set(..)` takes a `&self` reference, while according to rust mutability rules, you would expect it to require a `&mut self` reference. There are a lot of similar situations all around the binding.

Is it intended ?
(If not, I could maybe start working on fixing it everywhere appropriate, if I find some time.)

**Comment by GuillaumeGomez** [comment]
I did it at my beginnings because I had a warning about useless mutability. So this is half intended. I didn't get back to it since then. It would be very nice if you did correct it !

**Comment by iduartgomez** [comment]
I don't think this can be closed yet, as there are other types (besides matrix/vectors) and functions that need some references to be changed to &mut, I'll be changing them exhaustively but the library is large so it may take a while if we don't want to miss any.

**Comment by GuillaumeGomez** [comment]
That's because your comment had "fixes #7". I reopen it.

**Comment by GuillaumeGomez** [comment]
Fixed by #41 and #43.
