### ISSUE TITLE
Publiciting it on GSL site

### ISSUE THREAD

**Issue by rasa200** [GuillaumeGomez/rust-GSL#76]
Hi there! Thank you for the hard work!!

I noticed that there is no mention of this wrapper in the [GSL site](http://www.gnu.org/software/gsl/), in the section `Wrappers for Other Languages (not necessarily complete):`. 

You might want to rise an issue there to be included.

Cheers!

**Comment by GuillaumeGomez** [comment]
I did years ago. No answer. If you want to give it a try? :)

**Comment by rasa200** [comment]
I will give it a try!!
