### ISSUE TITLE
Mathieu functions always return zero

### ISSUE THREAD

**Issue by Jvanrhijn** [GuillaumeGomez/rust-GSL#78]
The Mathieu functions provided in `types::mathieu::MathieuWorkspace` always return zero. Example:

~~~rust
use rgsl::types::mathieu::MathieuWorkspace;
use rgsl::Value;

fn main() {
    const Q: f64 = 0.8253525490491695;
    let foo = match MathieuWorkspace::mathieu_Mc(1, 0, Q, 0.5) {
        (Value::Success, res) => res.val,
        _ => panic!("Mathieu function failed"),
    };
    println!("{}", foo);
}
~~~

Output: `0`. This seems to happen for any input.

By contrast, for a roughly equivalent C program:

~~~c
#include <stdio.h>
#include "gsl/gsl_sf_mathieu.h"


int main() {
    double q = 0.8253525490491695;
    gsl_sf_result res;
    gsl_sf_mathieu_Mc_e(1, 0, q, 0.5, &res);
    printf("%f", res.val);
}
~~~

I get `0.666843`.

**Comment by Jvanrhijn** [comment]
The issue seems to be that the wrong (non error-handling) C functions are being called. These just return the function value, so the `gsl_sf_result` struct stays zeroed out. Replacing `gsl_sf_mathieu_Mc` with `gsl_sf_mathieu_Mc_e` [here](https://github.com/GuillaumeGomez/rust-GSL/blob/master/src/ffi/mod.rs#L1255) and 
[here](https://github.com/GuillaumeGomez/rust-GSL/blob/master/src/types/mathieu.rs#L107) fixes the problem in the above snippet. Fixing it for all the Mathieu functions in `types/mathieu.rs` should be easy enough, if tedious.

**Comment by GuillaumeGomez** [comment]
I was taking a look. Want to send a patch maybe?

**Comment by GuillaumeGomez** [comment]
Something else to be careful of: the version in which it was added. It's super annoying to find this information...

**Comment by Jvanrhijn** [comment]
Sure, I'll get on that in a bit. What do you mean, to be careful of the version in which it was added?

**Comment by GuillaumeGomez** [comment]
If it's been added in a newer version than the default one we rely on, we'll need to add a `cfg` condition on the function.

**Comment by Jvanrhijn** [comment]
Far as I can tell, the Mathieu stuff was added in v1.9: https://abi-laboratory.pro/?view=changelog&l=gsl&v=1.9

What version does rgsl depend on by default?

**Comment by GuillaumeGomez** [comment]
Version 1.9? So it's gonna be fine. The default version is 1.X, so starting 2.X, you have to put behind a feature.
