### ISSUE TITLE
Incorrect ffi-binding to gsl_multifit_function_fdf

### ISSUE THREAD

**Issue by hombit** [GuillaumeGomez/rust-GSL#82]
GSL header [`gsl_multifit_nlin.h` specifies](http://git.savannah.gnu.org/cgit/gsl.git/tree/multifit/gsl_multifit_nlin.h?h=release-2-6&id=8f0165f5cb2ae02e386cd33ff10e47ffb46ea7da#n108) `gsl_multifit_function_fdf` as

```C
struct gsl_multifit_function_fdf_struct
{
  int (* f) (const gsl_vector * x, void * params, gsl_vector * f);
  int (* df) (const gsl_vector * x, void * params, gsl_matrix * df);
  int (* fdf) (const gsl_vector * x, void * params, gsl_vector * f, gsl_matrix *df);
  size_t n;       /* number of functions */
  size_t p;       /* number of independent variables */
  void * params;  /* user parameters */
  size_t nevalf;  /* number of function evaluations */
  size_t nevaldf; /* number of Jacobian evaluations */
};

typedef struct gsl_multifit_function_fdf_struct gsl_multifit_function_fdf ;
```

but Rust ffi binding misses last two fields:
https://github.com/GuillaumeGomez/rust-GSL/blob/b06c6732fd1155825141b28844f764cb396907dc/src/ffi/solvers.rs#L150-L168

I noticed this when saw undefined behaviour of my Rust code: some of my variables are changed by `MultiFitFSolver::set()`, but I didn't passed them there. Probably it also can cause problems described by #67

**Comment by GuillaumeGomez** [comment]
I'm currently writing the script to check that the Rust bindings are correct. I realized that a few types/functions had mismatching definitions compared to the C one.

**Comment by hombit** [comment]
Can the ffi bindings be generated by `bindgen`?

**Comment by GuillaumeGomez** [comment]
Yes but I don't like the generated code.

**Comment by GuillaumeGomez** [comment]
This issue was fixed when we (finally) switched to automated FFI code generation.
