### ISSUE TITLE
Trouble with linking

### ISSUE THREAD

**Issue by Genarito** [GuillaumeGomez/rust-GSL#94]
Hi! First of all thak you for this amazing crate!
I opened [an issue in Pyo3](https://github.com/PyO3/maturin/issues/387) repo as I want to use my code written in Rust (which uses this crate) from Python. The problem is that in the issue the author mentioned that It could be a link problem of this crate.
I honestly do not know how library linking works, so I opened this issue to know if I'm missing something or if there is a problem in this repo with gsl-sys.
P.D: Sorry about my English

**Comment by GuillaumeGomez** [comment]
It can be two things: invalid linking or a too olid library. The `gsl_stat_spearman` was added in the 2.6 version. Maybe check the gsl version in your docker first?

**Comment by Genarito** [comment]
You're right! The Maturin's Docker image has an old CentOS which offers the version `1.13` of GSL. I'll try to fix the image, install a version > 2.6 and tell you. Thank you so much!

**Comment by Genarito** [comment]
Works like a charm! Thank sooo much for your help!
