### ISSUE TITLE
Failing to compile under Rust 1.51.0

### ISSUE THREAD

**Issue by Pardoxa** [GuillaumeGomez/rust-GSL#95]
I just updated to the newest version of rustc (1.51.0) and now I cannot build the GSL crate (3.0.0).
I get the following Error:
```
error: `#[doc(alias = "...")]` is the same as the item's name
   --> /home/yannick/.cargo/registry/src/github.com-1ecc6299db9ec823/GSL-3.0.0/src/stats.rs:150:7
    |
150 | #[doc(alias = "gsl_stats_minmax")]
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: `#[doc(alias = "...")]` is the same as the item's name
   --> /home/yannick/.cargo/registry/src/github.com-1ecc6299db9ec823/GSL-3.0.0/src/stats.rs:170:7
    |
170 | #[doc(alias = "gsl_stats_minmax_index")]
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: could not compile `GSL`
```

I have the same problem with nightly rust (1.53.0). However reverting back to 1.50.0 (rustup override set 1.50.0) fixes the issue,
though now I cannot use newer rust compilers for my project

**Comment by GuillaumeGomez** [comment]
Fun part being that I'm the one who implemented that lint haha. Thanks for the report, fixing it quickly!
