### ISSUE TITLE
Spline::init can read uninitialized memory

### ISSUE THREAD

**Issue by shradej1** [GuillaumeGomez/rust-GSL#98]
https://github.com/GuillaumeGomez/rust-GSL/blob/234cfc26deef8b096e5e8c6a34e0463f5e89bc74/src/types/interpolation.rs#L111

The size of `ya` is never checked, and is simply assumed to be valid for `xa.len()` elements.  If `xa.len()` is larger than the size passed to `Spline::new()`, the gsl error handler is called.  But if the length of `ya` doesn't match, no such error occurs.  I wonder if this should `assert_eq!(xa.len(), ya.len())`?

**Comment by GuillaumeGomez** [comment]
I think it'd be better to check this:

```rust
assert!(ya.len() >= xa.len());
```

But otherwise you're absolutely right! Want to send a fix?
